# Generated by Django 3.0.2 on 2020-03-21 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('mothijheel', 'Mothijheel'), ('bonosree', 'Bonosree'), ('mirpur', 'Mirpur'), ('khilgao', 'Khilgao'), ('gulshan', 'Gulshan'), ('badda', 'Badda'), ('uttora', 'Uttora'), ('banani', 'Banani')], max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('bedroom', models.PositiveSmallIntegerField()),
                ('bathroom', models.PositiveSmallIntegerField()),
                ('rent', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.PositiveIntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='house_pics/')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BariVara.advertisements')),
            ],
        ),
    ]
